//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Entity_Frame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autoriu
    {
        public Autoriu()
        {
            this.Dainas = new HashSet<Daina>();
        }
    
        public int Id { get; set; }
        public string Autorius { get; set; }
        public string Tautybe { get; set; }
    
        public virtual ICollection<Daina> Dainas { get; set; }
    }
}
