//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muzika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albumas
    {
        public string Pavadinimas { get; set; }
        public Nullable<double> Turinis_Min { get; set; }
        public string Atlikejas { get; set; }
    
        public virtual Atlikejas OAtlikejas { get; set; }
    }
}
