//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muzika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BloggingContext : DbContext
    {
        public BloggingContext()
            : base("name=BloggingContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atlikejas> Atlikejai { get; set; }
        public virtual DbSet<Albumas> Albumai { get; set; }
        public virtual DbSet<Autorius> Autoriai { get; set; }
        public virtual DbSet<Daina> Dainos { get; set; }
        public virtual DbSet<Priklauso> Priklausantys { get; set; }
    }
}
