//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muzika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daina
    {
        public Daina()
        {
            this.Zanras = "Nenustatyta";
        }
    
        public string Pavadinimas { get; set; }
        public Nullable<double> Trukme_Min { get; set; }
        public string Zanras { get; set; }
        public int Autorius { get; set; }
    
        public virtual Autorius OAutorius { get; set; }
    }
}
